apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox
    image: node:18-alpine 
    command: ["/bin/sh", "-c", "while true; do nodejs /config/test-dns.js; done"]
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: query-script-js
      defaultMode: 0777
